#!/bin/bash

# Copyright (c) 2011, Joshua V Dillon
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#  * Redistributions of source code must retain the above
#    copyright notice, this list of conditions and the
#    following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the
#    following disclaimer in the documentation and/or other
#    materials provided with the distribution.
#  * Neither the name of the author nor the names of its
#    contributors may be used to endorse or promote products
#    derived from this software without specific prior written
#    permission.
# 
# THIS SOFTWARE IS PROVIDED BY JOSHUA V DILLON ''AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL JOSHUA
# V DILLON BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# matlabd:
# Bash script to allow communication to a Matlab pipe.
#
# Author:
# Joshua V Dillon
#
# Revision History:
# Jan. 20. 2011  First release.
#
# @ Michael Tetemke Mehari
# July. 31. 2016  Second release.

if [[ ! -p /tmp/mlpipe ]]; then 
	mkfifo /tmp/mlpipe; 
fi

# Some times when listing open files (i.e. lsof), fuse filesystem might complain. Redirect stderr to /dev/null
if [[ -z "$(lsof /tmp/mlpipe 2>/dev/null)" ]]; then

	MATLAB=""
	CMD="tail -f /tmp/mlpipe | $MATLAB 1> /tmp/matlab.out 2>/tmp/matlab.err &"
	nohup bash -c "$CMD" &>/tmp/matlab.nohup

	sleep inf &
	echo "pwd;kill($!,9);" >/tmp/mlpipe
	wait &>/dev/null
fi

# Before commands are executed, empty output and error message holders
truncate -s 0 /tmp/matlab.out
truncate -s 0 /tmp/matlab.err

sleep inf &
PID=$!
if [[ -f "$*" ]]; then
	sed -u "1d;\$a\\" "$*" >/tmp/mlpipe 
else
	echo "try,$*,catch ME,disp(['ERROR: ' ME.message]); end;" >/tmp/mlpipe
fi
echo "kill($PID,9);" >/tmp/mlpipe
wait &>/dev/null

# Matlab by default places the prompt character (i.e. >>) at the end. Remove it
# Also remove preceding null characters from output and error message holders
#sed -e 's/\x0//g' -e ':a;N;$!ba;s/\n//g' -e '$ s/.\{6\}$//' /tmp/matlab.out
sed -e 's/\x0//g' -e '$ s/.\{6\}$//' /tmp/matlab.out
sed -e 's/\x0//g' /tmp/matlab.err 1>&2

